name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 3: Run Tests
      - name: Run Tests
        run: npm test

      # Step 4: Build the Project
      - name: Build Project
        run: npm run build

      # Step 5: Docker Setup (optional for deployment)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t camieladriaen/dockertestfilestorage-frontend:${{ github.sha }} .
          docker push camieladriaen/dockertestfilestorage-frontend:${{ github.sha }}
