name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 3: Set environment variables to ignore warnings
      - name: Set Environment Variables
        run: echo "CI=false" >> $GITHUB_ENV && echo "DISABLE_ESLINT_PLUGIN=true" >> $GITHUB_ENV

      # Step 4: Build the Project
      - name: Build Project
        run: npm run build

      # Step 5: Docker Setup (optional for deployment)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
# Step 13: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t camieladriaen/dockertestfilestorageclientapp:${{ github.sha }} .
      # Step 14: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push camieladriaen/dockertestfilestorageclientapp:${{ github.sha }}
